export {default as NavBar} from '../Components/NavBar'
export {default as ProjectsContent} from '../Components/ProjectsContent'
export {default as Home} from '../Pages/Home'
export {default as About} from '../Pages/About'
export {default as Projects} from '../Pages/Projects'
export {default as Button} from '../Components/Button'
export {default as ProjectData} from './ProjectData'